//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotonControl.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PhotonControlStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PhotonControlStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhotonControl.Resources.PhotonControlStrings", typeof(PhotonControlStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photon configuration errror.
        /// </summary>
        internal static string configFileNotFoundCaption {
            get {
                return ResourceManager.GetString("configFileNotFoundCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load photon configuration from.
        /// </summary>
        internal static string configFileNotFoundMsg {
            get {
                return ResourceManager.GetString("configFileNotFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        internal static string copyToClipboardToolStripMenuItemText {
            get {
                return ResourceManager.GetString("copyToClipboardToolStripMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Logging Set.
        /// </summary>
        internal static string createLoggingSetToolStripMenuItemText {
            get {
                return ResourceManager.GetString("createLoggingSetToolStripMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default.
        /// </summary>
        internal static string cultureInfo {
            get {
                return ResourceManager.GetString("cultureInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist.
        /// </summary>
        internal static string exceptionFileNotFound {
            get {
                return ResourceManager.GetString("exceptionFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed on call:.
        /// </summary>
        internal static string failedOnCallMsg {
            get {
                return ResourceManager.GetString("failedOnCallMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to query processes. Exception.
        /// </summary>
        internal static string failedProcessQueryMsg {
            get {
                return ResourceManager.GetString("failedProcessQueryMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to query services. Exception.
        /// </summary>
        internal static string failedServiceQueryMsg {
            get {
                return ResourceManager.GetString("failedServiceQueryMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to install dashboard service:.
        /// </summary>
        internal static string failedToInstallDashboardMsg {
            get {
                return ResourceManager.GetString("failedToInstallDashboardMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open dashboard:.
        /// </summary>
        internal static string failedToOpenDashboardMsg {
            get {
                return ResourceManager.GetString("failedToOpenDashboardMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove dashboard service:.
        /// </summary>
        internal static string failedToRemoveDashboardMsg {
            get {
                return ResourceManager.GetString("failedToRemoveDashboardMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to restart dashboard service:.
        /// </summary>
        internal static string failedToRestartDashboardMsg {
            get {
                return ResourceManager.GetString("failedToRestartDashboardMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start dashboard service:.
        /// </summary>
        internal static string failedToStartDashboardMsg {
            get {
                return ResourceManager.GetString("failedToStartDashboardMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to stop dashboard service:.
        /// </summary>
        internal static string failedToStopDashboardMsg {
            get {
                return ResourceManager.GetString("failedToStopDashboardMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to view logs:.
        /// </summary>
        internal static string failedToViewLogsMsg {
            get {
                return ResourceManager.GetString("failedToViewLogsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while adding Photon to firewall.
        /// </summary>
        internal static string firewallExceptionMsg {
            get {
                return ResourceManager.GetString("firewallExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photon requires .NET Framework v{0} or later. Please download and install the appropriate version from http://download.microsoft.com.
        /// </summary>
        internal static string frameworkVersionRequiredMsg {
            get {
                return ResourceManager.GetString("frameworkVersionRequiredMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Server Config Change Error.
        /// </summary>
        internal static string gameServerConfigChangeErrorCaption {
            get {
                return ResourceManager.GetString("gameServerConfigChangeErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Server config file invalid..
        /// </summary>
        internal static string gameServerConfigInvalidMsg {
            get {
                return ResourceManager.GetString("gameServerConfigInvalidMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to copy Photon server address..
        /// </summary>
        internal static string launcherCopyAddressText {
            get {
                return ResourceManager.GetString("launcherCopyAddressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set local IP. Can not start Photon..
        /// </summary>
        internal static string launcherFailedToSetIpText {
            get {
                return ResourceManager.GetString("launcherFailedToSetIpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photon failed to start. Check log files..
        /// </summary>
        internal static string launcherFailedToStartText {
            get {
                return ResourceManager.GetString("launcherFailedToStartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photon already running..
        /// </summary>
        internal static string launcherPhotonAlreadyRunningText {
            get {
                return ResourceManager.GetString("launcherPhotonAlreadyRunningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photon not running..
        /// </summary>
        internal static string launcherPhotonNotRunningText {
            get {
                return ResourceManager.GetString("launcherPhotonNotRunningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photon started at:.
        /// </summary>
        internal static string launcherPhotonStartedText {
            get {
                return ResourceManager.GetString("launcherPhotonStartedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photon starting....
        /// </summary>
        internal static string launcherPhotonStartingText {
            get {
                return ResourceManager.GetString("launcherPhotonStartingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photon stopped..
        /// </summary>
        internal static string launcherPhotonStoppedText {
            get {
                return ResourceManager.GetString("launcherPhotonStoppedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photon stopping....
        /// </summary>
        internal static string launcherPhotonStoppingText {
            get {
                return ResourceManager.GetString("launcherPhotonStoppingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you close this Window, Photon will be stopped..
        /// </summary>
        internal static string launcherPhotonStopWarningMsg {
            get {
                return ResourceManager.GetString("launcherPhotonStopWarningMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string launcherStartButtonText {
            get {
                return ResourceManager.GetString("launcherStartButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string launcherStopButtonText {
            get {
                return ResourceManager.GetString("launcherStopButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied server address to clipboard..
        /// </summary>
        internal static string launcherUdpAddressCopiedText {
            get {
                return ResourceManager.GetString("launcherUdpAddressCopiedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string launcherWaitButtonText {
            get {
                return ResourceManager.GetString("launcherWaitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 [no license].
        /// </summary>
        internal static string licenseBootstrapCCUText {
            get {
                return ResourceManager.GetString("licenseBootstrapCCUText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootstrap License.
        /// </summary>
        internal static string licenseBootstrapLicenseeText {
            get {
                return ResourceManager.GetString("licenseBootstrapLicenseeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Photon License expired on {0}. You should replace it. Contact developer@exitgames.com if you need assistance..
        /// </summary>
        internal static string licenseExpiredTipText {
            get {
                return ResourceManager.GetString("licenseExpiredTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License expired.
        /// </summary>
        internal static string licenseExpiredTipTitle {
            get {
                return ResourceManager.GetString("licenseExpiredTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No license file was found. Limiting the number of concurrent users (ccu) to 20..
        /// </summary>
        internal static string licenseNotFoundTipText {
            get {
                return ResourceManager.GetString("licenseNotFoundTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Photon License file.
        /// </summary>
        internal static string licenseNotFoundTipTitle {
            get {
                return ResourceManager.GetString("licenseNotFoundTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited.
        /// </summary>
        internal static string licenseUnlimitedCCUText {
            get {
                return ResourceManager.GetString("licenseUnlimitedCCUText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autostart Photon Control.
        /// </summary>
        internal static string miAutostartEnableText {
            get {
                return ResourceManager.GetString("miAutostartEnableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PerfMon Counters.
        /// </summary>
        internal static string miCountersText {
            get {
                return ResourceManager.GetString("miCountersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to autodetect public.
        /// </summary>
        internal static string miCurrentGameServerIPAutodetectText {
            get {
                return ResourceManager.GetString("miCurrentGameServerIPAutodetectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current IP.
        /// </summary>
        internal static string miCurrentGameServerIpText {
            get {
                return ResourceManager.GetString("miCurrentGameServerIpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install service.
        /// </summary>
        internal static string miDashboardInstallText {
            get {
                return ResourceManager.GetString("miDashboardInstallText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string miDashboardOpenText {
            get {
                return ResourceManager.GetString("miDashboardOpenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove service.
        /// </summary>
        internal static string miDashboardRemoveText {
            get {
                return ResourceManager.GetString("miDashboardRemoveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string miDashboardRestartText {
            get {
                return ResourceManager.GetString("miDashboardRestartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string miDashboardStartText {
            get {
                return ResourceManager.GetString("miDashboardStartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string miDashboardStopText {
            get {
                return ResourceManager.GetString("miDashboardStopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string miDashboardText {
            get {
                return ResourceManager.GetString("miDashboardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Photon Control.
        /// </summary>
        internal static string miExitControlText {
            get {
                return ResourceManager.GetString("miExitControlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires.
        /// </summary>
        internal static string miExpiresText {
            get {
                return ResourceManager.GetString("miExpiresText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore Working Path.
        /// </summary>
        internal static string miExploreText {
            get {
                return ResourceManager.GetString("miExploreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating license.
        /// </summary>
        internal static string miFloatingLicenseText {
            get {
                return ResourceManager.GetString("miFloatingLicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Your Free License.
        /// </summary>
        internal static string miFreeLicenseText {
            get {
                return ResourceManager.GetString("miFreeLicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware ID.
        /// </summary>
        internal static string miHardwareIDText {
            get {
                return ResourceManager.GetString("miHardwareIDText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Counters.
        /// </summary>
        internal static string miInstallCountersText {
            get {
                return ResourceManager.GetString("miInstallCountersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install service.
        /// </summary>
        internal static string miInstallServiceText {
            get {
                return ResourceManager.GetString("miInstallServiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current version.
        /// </summary>
        internal static string miLatestVersionText {
            get {
                return ResourceManager.GetString("miLatestVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensed for.
        /// </summary>
        internal static string miLicenseCompanyText {
            get {
                return ResourceManager.GetString("miLicenseCompanyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensed IPs.
        /// </summary>
        internal static string miLicensedIPsText {
            get {
                return ResourceManager.GetString("miLicensedIPsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensee mail.
        /// </summary>
        internal static string miLicenseeMailText {
            get {
                return ResourceManager.GetString("miLicenseeMailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Monitor: available.
        /// </summary>
        internal static string miLicenseMonitorAvailableIsAvailableText {
            get {
                return ResourceManager.GetString("miLicenseMonitorAvailableIsAvailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Monotir: not reached.
        /// </summary>
        internal static string miLicenseMonitorAvailableIsNotAvailableText {
            get {
                return ResourceManager.GetString("miLicenseMonitorAvailableIsNotAvailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Monitor: checking availability.
        /// </summary>
        internal static string miLicenseMonitorAvailableText {
            get {
                return ResourceManager.GetString("miLicenseMonitorAvailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License info.
        /// </summary>
        internal static string miLicenseText {
            get {
                return ResourceManager.GetString("miLicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Server IP Config.
        /// </summary>
        internal static string miLoadBalancingIpMenuText {
            get {
                return ResourceManager.GetString("miLoadBalancingIpMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Connections.
        /// </summary>
        internal static string miMaxConnectionsText {
            get {
                return ResourceManager.GetString("miMaxConnectionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Logs.
        /// </summary>
        internal static string miOpenLogsText {
            get {
                return ResourceManager.GetString("miOpenLogsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photon Control.
        /// </summary>
        internal static string miPhotonTitleText {
            get {
                return ResourceManager.GetString("miPhotonTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Counters.
        /// </summary>
        internal static string miRemoveCountersText {
            get {
                return ResourceManager.GetString("miRemoveCountersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Service.
        /// </summary>
        internal static string miRemoveServiceText {
            get {
                return ResourceManager.GetString("miRemoveServiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart service.
        /// </summary>
        internal static string miRestartServiceText {
            get {
                return ResourceManager.GetString("miRestartServiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run ProcDump.
        /// </summary>
        internal static string miRunProcDumpText {
            get {
                return ResourceManager.GetString("miRunProcDumpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Testclient.
        /// </summary>
        internal static string miRunTestclientText {
            get {
                return ResourceManager.GetString("miRunTestclientText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the latest version of Photon..
        /// </summary>
        internal static string miSdkVersionLatestVersionText {
            get {
                return ResourceManager.GetString("miSdkVersionLatestVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer version of Photon is available..
        /// </summary>
        internal static string miSdkVersionNewerVersionText {
            get {
                return ResourceManager.GetString("miSdkVersionNewerVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string miSdkVersionText {
            get {
                return ResourceManager.GetString("miSdkVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Autodetect Public IP.
        /// </summary>
        internal static string miSetAutodetectIpText {
            get {
                return ResourceManager.GetString("miSetAutodetectIpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Local IP.
        /// </summary>
        internal static string miSetLocalIpText {
            get {
                return ResourceManager.GetString("miSetLocalIpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Public IP.
        /// </summary>
        internal static string miSetPublicIpText {
            get {
                return ResourceManager.GetString("miSetPublicIpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start as application.
        /// </summary>
        internal static string miStartAppText {
            get {
                return ResourceManager.GetString("miStartAppText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start PerfMon.
        /// </summary>
        internal static string miStartPerfmonText {
            get {
                return ResourceManager.GetString("miStartPerfmonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start service.
        /// </summary>
        internal static string miStartServiceText {
            get {
                return ResourceManager.GetString("miStartServiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop application.
        /// </summary>
        internal static string miStopAppText {
            get {
                return ResourceManager.GetString("miStopAppText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop service.
        /// </summary>
        internal static string miStopServiceText {
            get {
                return ResourceManager.GetString("miStopServiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhotonControl Error.
        /// </summary>
        internal static string photonControlErrorCaption {
            get {
                return ResourceManager.GetString("photonControlErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photon instances:.
        /// </summary>
        internal static string photonInstancesToolStripMenuItemText {
            get {
                return ResourceManager.GetString("photonInstancesToolStripMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not start Photon.
        /// </summary>
        internal static string photonStartExceptionMsg {
            get {
                return ResourceManager.GetString("photonStartExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not stop Photon.
        /// </summary>
        internal static string photonStopExceptionMsg {
            get {
                return ResourceManager.GetString("photonStopExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to multipleInstances.
        /// </summary>
        internal static string programAlreadyRunningCaption {
            get {
                return ResourceManager.GetString("programAlreadyRunningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photon Control is already running!\nCheck tray bar..
        /// </summary>
        internal static string programAlreadyRunningMsg {
            get {
                return ResourceManager.GetString("programAlreadyRunningMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Logging Set.
        /// </summary>
        internal static string removeLoggingSetToolStripMenuItemText {
            get {
                return ResourceManager.GetString("removeLoggingSetToolStripMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting&apos;{0}&apos;service failed. Exception:.
        /// </summary>
        internal static string serviceStartingFailedMsg {
            get {
                return ResourceManager.GetString("serviceStartingFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping &apos;{0}&apos; service failed. Exception:.
        /// </summary>
        internal static string serviceStoppingFailedMsg {
            get {
                return ResourceManager.GetString("serviceStoppingFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Logging.
        /// </summary>
        internal static string startLoggingToolStripMenuItemText {
            get {
                return ResourceManager.GetString("startLoggingToolStripMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Logging.
        /// </summary>
        internal static string stopLoggingToolStripMenuItemText {
            get {
                return ResourceManager.GetString("stopLoggingToolStripMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tester config is broken. Can&apos;t start the tester..
        /// </summary>
        internal static string testClientConfigErrorMsg {
            get {
                return ResourceManager.GetString("testClientConfigErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open testclient.
        /// </summary>
        internal static string testClientFailedMsg {
            get {
                return ResourceManager.GetString("testClientFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No logs of the past 12 hours found. Select them manually if needed..
        /// </summary>
        internal static string trayIconNoLogFoundTipText {
            get {
                return ResourceManager.GetString("trayIconNoLogFoundTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open logs.
        /// </summary>
        internal static string trayIconNoLogFoundTipTitle {
            get {
                return ResourceManager.GetString("trayIconNoLogFoundTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photon stopped.
        /// </summary>
        internal static string trayIconText {
            get {
                return ResourceManager.GetString("trayIconText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photon running.
        /// </summary>
        internal static string trayIconTextRunning {
            get {
                return ResourceManager.GetString("trayIconTextRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photon stopped.
        /// </summary>
        internal static string trayIconTextStopped {
            get {
                return ResourceManager.GetString("trayIconTextStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for service.
        /// </summary>
        internal static string waitingForServiceText {
            get {
                return ResourceManager.GetString("waitingForServiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please wait.
        /// </summary>
        internal static string waitText {
            get {
                return ResourceManager.GetString("waitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes333333333333.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
