//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photon.SocketServer.Web {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class HttpSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static HttpSettings defaultInstance = ((HttpSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new HttpSettings())));
        
        public static HttpSettings Default {
            get {
                return defaultInstance;
            }
        }

        /// <summary>
        ///  The Ping frequency is how often a ping is sent out for server to server connections when no data is flowing.
        /// </summary>       
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2500")]
        public int S2SPingFrequency {
            get {
                return ((int)(this["S2SPingFrequency"]));
            }
        }
    }
}
